MattDrennan/GreenworksMap

- EcoMap/src/main/webapp/admin.jsp
This is a test to verify that I am moving files to where they should go.
> Made a minor fix to the navbar.

- EcoMap/src/main/java/com/GREENWORKS/eco/DatabaseConstants.java
- EcoMap/src/main/java/com/GREENWORKS/eco/MysqlConnect.java
I moved the database-related constants to their own DatabaseConstants file. After this merge to master it might be necessary to **respecify the USERNAME, PASSWORD, and DATABASE_URL**. I also updated the MysqlConnect file to use the variables in the DatabaseConstants. I added some accessor and mutator methods for the MysqlConnect instance variables. These new methods, as well as the existing methods, will be used for testing purposes. 
Intent: Project Organization, Unit Testing, & Documentation
> DatabaseConstants & MysqlConnect

- EcoMap/src/main/webapp/index.jsp
- EcoMap/src/main/webapp/scripts/main.js
- EcoMap/src/main/webapp/scripts/mapEmbed.js
A working filter to filter out markers without refreshing the page.
> JQuery Filter

- EcoMap/pom.xml
- EcoMap/src/test/java/MysqlConnectTests.java
Added unit testing into the build process. Created unit tests for MysqlConnect.java.
> Unit Tests for MysqlConnect. Intent: Unit Testing

- EcoMap/src/main/java/com/GREENWORKS/eco/EcoMap.java
- EcoMap/src/test/java/EcoMapTests.java
- README.md
> Updating the Readme to include the TomCat 9 incompatibility.

- EcoMap/src/test/java/EcoMapTests.java
Added a test verify the functionality of EcoMap.CredentialCheck(). 
Intent: Unit Testing
> Added the credentialCheck unit test for EcoMap. Intent: Unit Testing

- EcoMap/pom.xml
- EcoMap/src/main/java/com/GREENWORKS/eco/MysqlConnect.java
- EcoMap/src/main/resources/tinylog.properties
Adding tinylog to the pom.xml, tinylog properties file, and implemented logging in MysqlConnect.
> Added logging to the project

- EcoMap/pom.xml
- EcoMap/src/main/java/com/GREENWORKS/eco/MysqlConnect.java
- EcoMap/src/main/resources/tinylog.properties
Reverts MattDrennan/GreenworksMap#16
Logging isn't being implemented on Tomcat the way I want it to. Reverting until I find a solution.
> Revert "Added logging to the project"

- EcoMap/src/main/java/com/GREENWORKS/eco/EditLocationSave.java
- EcoMap/src/test/java/EditLocationsSaveTests.java
Changes to EditLocationSave.java
- Added logging
- Minor refactoring to increase testability
- Minor documentation. 
Created the unit tests for EditLocationSave.java. 
Intent: Refactoring, Unit Testing, and Documentation
> Added unit tests for EditLocationSave.java also implemented logging.

- EcoMap/src/main/java/com/GREENWORKS/eco/data/PinData.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/PinDataAbstractFactory.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/package-info.java
- EcoMap/src/test/java/DataPackageTests.java
This includes the PinData super class, the AbstractFactory, and the unit tests. The PinData's children Location and Event are located in the AbstractFactory.
> Abstract factory with data classes.

- EcoMap/src/main/java/com/GREENWORKS/eco/data/PinData.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/PinDataAbstractFactory.java
- EcoMap/src/test/java/DataPackageTests.java
Making some specific updates for compatibility with EditSaveLocation.java.
> Abstract factory with data classes. -Update

- EcoMap/src/main/java/com/GREENWORKS/eco/data/PinData.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/PinDataAbstractFactory.java
- EcoMap/src/test/java/DataPackageTests.java
The documentation for the data package and its unit tests should be finished. 
Intent: Documentation
> Added documentation to the data package and its unit tests.

- EcoMap/src/main/java/com/GREENWORKS/eco/data/PinData.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/PinDataAbstractFactory.java
- EcoMap/src/test/java/DataPackageTests.java
Updated the data package and unit tests for the ArcGIS changes.
> Abstract factory with data classes updated for ArcGIS.

- EcoMap/src/test/java/DataPackageTests.java
Fixing some broken unit tests. 
Intent: Unit testing
> Fixing the data tests.

- EcoMap/src/main/java/com/GREENWORKS/eco/data/EventPin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/GenericPin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/LocationPin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/Pin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/PinFactory.java
- EcoMap/src/test/java/DataPackageTests.java
Renamed some files and added a GenericPin.java.
> Doing some refactoring so the names make more sense.

- EcoMap/src/test/java/DataPackageTests.java
Add a little documentation and adjusted some unit tests to simulate object-relational mapping functionality. 
Intent: Unit Testing & Documentation
> Adding documentation and adjusting tests.

- EcoMap/src/main/java/com/GREENWORKS/eco/data/Pin.java
- EcoMap/src/main/java/hibernate.cfg.xml
- EcoMap/src/main/webapp/scripts/esri_api.js
- EcoMap/src/test/java/DataPackageTests.java
Figured out how to change opacity in the js.
> Added opacity to the polygon.

- EcoMap/src/main/java/com/GREENWORKS/eco/data/Admin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/GenericPin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/Pin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/PinFactory.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionAssistant.java
- EcoMap/src/test/java/DataPackageTests.java
Intent: Hibernate & Unit Testing
> Working on getting all Hibernate necessities implemented

- EcoMap/src/main/java/com/GREENWORKS/eco/data/Admin.java
> Fix table name.

- EcoMap/src/main/java/com/GREENWORKS/eco/Login.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/Admin.java
Implemented Hibernate for the Login servlet.
> Implemented Hibernate for the Login servlet.

- EcoMap/src/main/java/com/GREENWORKS/eco/data/EventPin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/LocationPin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/Pin.java
- EcoMap/src/test/java/DataPackageTests.java
- EcoMap/src/test/java/SessionAssistantTests.java
Doing some refining and syncing the database tables.
Getting ready to implement hibernate throughout the backend.
> Doing some refining and syncing the database tables.

- EcoMap/src/main/java/com/GREENWORKS/eco/data/EventPin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/GenericPin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/LocationPin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/Pin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionAssistant.java
- EcoMap/src/test/java/SessionAssistantTests.java
> Minor tweaking to hibernate.

- EcoMap/src/main/java/com/GREENWORKS/eco/data/Pin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionAssistant.java
- EcoMap/src/test/java/DataPackageTests.java
- EcoMap/src/test/java/SessionAssistantTests.java
Made changes to the data classes so that they can cater to the needs of the front-end.
> Implementing support for index.jsp

- EcoMap/src/main/java/com/GREENWORKS/eco/AddItem.java
- EcoMap/src/main/java/com/GREENWORKS/eco/EditLocation.java
- EcoMap/src/main/java/com/GREENWORKS/eco/EditLocationSave.java
- EcoMap/src/main/java/com/GREENWORKS/eco/Login.java
- EcoMap/src/main/java/com/GREENWORKS/eco/Logout.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionAssistant.java
- EcoMap/src/test/java/SessionAssistantTests.java
> Adding SessionAssistant documentation.

- EcoMap/src/main/java/com/GREENWORKS/eco/MysqlConnect.java
- EcoMap/src/main/java/com/GREENWORKS/eco/constants/DatabaseConstants.java
- EcoMap/src/main/java/com/GREENWORKS/eco/servlets/AddItem.java
- EcoMap/src/main/java/com/GREENWORKS/eco/servlets/EditLocation.java
- EcoMap/src/main/java/com/GREENWORKS/eco/servlets/EditLocationSave.java
- EcoMap/src/main/java/com/GREENWORKS/eco/servlets/Login.java
- EcoMap/src/main/java/com/GREENWORKS/eco/servlets/Logout.java
- EcoMap/src/main/java/com/GREENWORKS/eco/servlets/package-info.java
- EcoMap/src/test/java/DataPackageTests.java
- EcoMap/src/test/java/EcoMapTests.java
- EcoMap/src/test/java/MysqlConnectTests.java
Conducting some project structure modifications. DatabaseConstants has been moved to the constants package. Servlets have been moved to their own package. Unit tests have been updated.
> Just moving DatabaseConstants to the constants package. 

- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionAssistant.java
Made some methods generic and implemented the entry count methods.
> Updating SessionAssistant

- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionAssistant.java
- EcoMap/src/main/resources/readme.txt
- EcoMap/src/test/java/DataPackageTests.java
- README.md
Added a few unit tests for the data package.
> Expanding test coverage

- EcoMap/src/main/java/com/GREENWORKS/eco/OrlandoWebScraper.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/Pin.java
- altecomap.sql
> Created a web scraper for the city of orlando website.

- EcoMap/src/main/java/com/GREENWORKS/eco/data/ProblemPin.java
- EcoMap/src/test/java/DataPackageTests.java
- EcoMap/src/test/java/SessionAssistantTests.java
Minor changes. Implemented ProblemPin in unit tests.
> Minor fixes.

- EcoMap/src/main/webapp/stylesheets/ecomap_stylesheet.css
Adjusted CSS to properly show zoom control. #53
> Adjust Appearance of Zoom Controls #53

- EcoMap/src/main/webapp/admin.jsp
- EcoMap/src/main/webapp/stylesheets/admin-login.css
Updated the design and feel of the admin login screen. Made it mobile friendly.
Mobile view:
Desktop View:
> redesigned the admin login form, made it mobile friendly

- EcoMap/src/main/java/com/GREENWORKS/eco/data/DatabaseCleaner.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/OldEventPin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/Pin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/ProblemPin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionAssistant.java
- EcoMap/src/main/java/com/GREENWORKS/eco/servlets/CleanDatabase.java
Added the DatabaseCleaner.java. At this time, it is run through the main method within the DatabaseCleaner.java class, however, it would be good to have an automated implementation later. The cleaner goes through every database entry and separates entries that have the same address. It determines which redundant entry is the best version, and keeps that version in the locations table. Rather than outright discarding the non-ideal redundant entry occurrences, they are saved in the problem table.
> Implementing the database cleaner.

- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionAssistant.java
Trying to fix a possible memory leak cause.
> Added session close statements.

- EcoMap/Dockerfile
- EcoMap/src/main/webapp/admin.jsp
Added dockerfile and a little admin.jsp change.
> Ejnproject

- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionAssistant.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionFactoryUtility.java
Should improve operating performance.
> Broke the sessionfactory out of the sessionassistant instance

- EcoMap/src/main/java/com/GREENWORKS/eco/data/EventPin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/Pillar.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/Pin.java
- EcoMap/src/main/webapp/index.jsp
- EcoMap/src/test/java/SessionAssistantTests.java
- datainsert.sql
Included the 0 pillar and sub pillar types in the datainsert.sql. 
Changed how Longitude and Latitude is accessed in the frontend to reduce unnecessary computations. 
Also switched from iconid to pillar id.
> Minor Changes

- EcoMap/pom.xml
- EcoMap/src/main/java/com/GREENWORKS/eco/data/DatabaseCleaner.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/Pin.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionAssistant.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/SubPillar.java
- EcoMap/src/main/java/com/GREENWORKS/eco/servlets/AddItem.java
- EcoMap/src/main/java/com/GREENWORKS/eco/servlets/EditPillar.java
- EcoMap/src/main/java/com/GREENWORKS/eco/servlets/EditSubPillar.java
- EcoMap/src/main/webapp/admin.jsp
- EcoMap/src/test/java/SessionAssistantTests.java
- README.md
Adding the servlets for editing the SubPillars and Pillars.
Admin panel needs to implement these servlets.
> Adding the servlets for editing the SubPillars and Pillars.

- EcoMap/src/main/java/com/GREENWORKS/eco/data/Data.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/DatabaseCleaner.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionAssistant.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionFactoryUtility.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/SubPillar.java
- EcoMap/src/main/java/com/GREENWORKS/eco/threads/OldEventCleanerThread.java
Going to test this change on the server.
> Making adjustments

- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionAssistant.java
- EcoMap/src/main/java/com/GREENWORKS/eco/data/SessionFactoryUtility.java
- EcoMap/src/test/java/SessionAssistantTests.java
Scaling down the intensity of the SessonAssistantTests to significantly reduce the stress on the server during pipeline build. Also included a test version for the SessionFactoryUtility.
> Improving Build Time
